// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSystem_WebAPI.Data;

namespace SmartSystem_WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221112022721_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SmartSystem_WebAPI.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sigla")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Escritorio",
                            Sigla = "Esc"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Cozinha",
                            Sigla = "COZ"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Oficina",
                            Sigla = "OFC"
                        });
                });

            modelBuilder.Entity("SmartSystem_WebAPI.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Foto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("RG")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartamentoId = 1,
                            Foto = "Foto",
                            Nome = "Naruto",
                            RG = 102030
                        },
                        new
                        {
                            Id = 2,
                            DepartamentoId = 2,
                            Foto = "Foto",
                            Nome = "Goku",
                            RG = 301020
                        },
                        new
                        {
                            Id = 3,
                            DepartamentoId = 3,
                            Foto = "Foto",
                            Nome = "Yoga",
                            RG = 203010
                        });
                });

            modelBuilder.Entity("SmartSystem_WebAPI.Models.Funcionario", b =>
                {
                    b.HasOne("SmartSystem_WebAPI.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });
#pragma warning restore 612, 618
        }
    }
}
